name = "server"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDZkODdiNDUtNDkwNC00MzE3LThjNTctZTgzMDU1ZWE3ZWU3IiwidGVuYW50X2lkIjoiOWYzM2E1NDE3MTZkYzdjMWE3NDZhOTdkZjMzNmE3ZWY4Yjk4MDYwODVhMDEzYzQzYWJiMmRhOWQ3OWY3NDRmYyIsImludGVybmFsX3NlY3JldCI6IjEwZWNlMWI1LTNjZDItNDgwYS1hNWUzLTg2ZWIwOWE4ZGIxNyJ9.RWq3t-URy9fyF2cE7MznkYcTOea5HRM-9hViLQyMbtk"
JWT_SECRET = "vfgfdxh"
